### ISSUE TITLE
Change Suggestions

### ISSUE THREAD

**Issue by HENRYKC24** [aliabbani/Conference-page#2]
## Suggestions:pray:
- We suggest the mobile menu should cover the entire screen and also stop the body from scrolling. In that way, Your users will focus on the menu without getting distracted by other content.
#### code example
``` 
     .mobile-menu {
        height: 100%;
        ...
    }
    
    .body {
      height: 100%;
      overflow-y: hidden;
   }
```
- The "Main Program" section items in the home page should have a hover effect of white border, we think. This was implemented in the design template, but you can treat this as optional.
#### code example
```
.each-program:hover {
  border: solid #fff;
}
```
![GitHub Logo](https://0x0.st/-4E2.png)
- You may want to add margin-bottom to the speaker's name title to give them nice spacing. Maybe reduce the opacity of the floating background images in the header section. This is because it's interfering with the actual content of both the home and about page.
-When you hover over the past activities, maybe you should make the cursor
-  think it would be better to use another unit for sizing the Logos in the partner section, which makes your logos not stretching and distorted in the mobile size: you should add the Home link in the menu links to the home page.
- It would be better to remove the border of the join button just to follow the design template that is provided by Microverst.
- It's better to make the header without margin to make your website looks more professional

Ali, these are all suggestions we think will make your website look better:ok_hand:
Good job:+1:

**Comment by aliabbani** [comment]
Thank you for all these suggestions, I worked on all of them.
